version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-jwt-management-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.docker
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: targetit_db
    ports: 
      - "3306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
