version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: targetit_db
    ports: 
      - "3306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
